services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
       - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm run dev
  
  artificial_intelligence:
    build: ./artificial_intelligence
    container_name: carrotec_ai
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo
    networks:
      - carrotec_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  carrotec_network:
    driver: bridge
